include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    todo: info

linter:
  rules:
    - sort_pub_dependencies
    - sort_constructors_first
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - camel_case_types
    - directives_ordering
    - file_names
    - prefer_expression_function_bodies
    - no_literal_bool_comparisons
    - prefer_final_in_for_each
    - prefer_function_declarations_over_variables
    - 