include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    todo: info

linter:
  rules:
    # Existing rules
    - sort_pub_dependencies
    - sort_constructors_first
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - camel_case_types
    - directives_ordering
    - file_names
    - prefer_expression_function_bodies
    - no_literal_bool_comparisons
    - prefer_final_in_for_each
    - prefer_function_declarations_over_variables

    # Code organization and consistency
    - prefer_final_fields
    - prefer_final_locals
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_const_declarations
    - unnecessary_const
    - unnecessary_new
    - avoid_redundant_argument_values
    - sort_child_properties_last

    # Naming conventions
    - camel_case_extensions
    - constant_identifier_names
    - library_names
    - library_prefixes
    - non_constant_identifier_names
    - package_names

    # Type annotations and safety
    - always_declare_return_types
    - prefer_typing_uninitialized_variables
    - unnecessary_nullable_for_final_variable_declarations
    - type_annotate_public_apis
    - omit_local_variable_types

    # Performance and best practices
    - avoid_function_literals_in_foreach_calls
    - prefer_for_elements_to_map_fromIterable
    - prefer_if_elements_to_conditional_expressions
    - prefer_spread_collections
    - unnecessary_lambdas
    - unnecessary_string_interpolations
    - unnecessary_parenthesis

    # Error prevention
    - avoid_empty_else
    - avoid_returning_null_for_future
    - cancel_subscriptions
    - close_sinks
    - control_flow_in_finally
    - empty_catches
    - hash_and_equals
    - invariant_booleans
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - prefer_void_to_null
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_statements
    - unrelated_type_equality_checks
    - use_build_context_synchronously
    - valid_regexps
    - avoid_slow_async_io
    - comment_references