name: card_battler
description: "Card Battler Game built with Flutter and Flame"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flame: ^1.30.1
  flutter:
    sdk: flutter

dev_dependencies:
  flame_test: ^1.16.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/images/
    - assets/images/cards/light/item/560/
    - assets/images/cards/light/item/60/
