name: card_battler
description: "Card Battler Game built with Flutter and Flame"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.30.1

dev_dependencies:
  flame_test: ^1.16.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/enemy_cards.json
    - assets/data/shop_cards.json
    - assets/data/hero_starting_cards.json
